apiVersion: v1
kind: ReplicationController
metadata:
  name: server1-rc
  labels:
    service: server
spec:
  replicas: 3
  selector:
    app: nginx-service1
  template:
    metadata:
      labels:
        app: nginx-service1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
