apiVersion: v1               # Specifies the API version used to create the object.
kind: ReplicationController  # Defines the type of Kubernetes object, which is a ReplicationController in this case.
metadata:
  name: server2-rc             # The name of the ReplicationController. Must be unique within the namespace.
  labels:                    # Labels are key-value pairs attached to objects.
    service: server          # This label helps identify and group the Pods created by the ReplicationController.
spec:
  replicas: 3                # The desired number of Pod replicas that should be running.
  selector:                  # The selector used to identify the Pods managed by this ReplicationController.
    app: nginx-service2         # Pods with this label will be managed by this ReplicationController.
  template:                  # The Pod template that defines how the Pods should be created.
    metadata:
      labels:
        app: nginx-service2    # Labels for the Pods created by this ReplicationController.
    spec:
      containers:            # The list of containers that will run in the Pod.
      - name: nginx          # The name of the container within the Pod.
        image: nginx         # The Docker image used to run the container. Here, it’s the official Nginx image.
        ports:               # Specifies the list of ports to expose from the container.
        - containerPort: 80  # The port that will be exposed by the container. Commonly used by Nginx.
          protocol: TCP      # The protocol used for the exposed port, usually TCP or UDP.
