apiVersion: v1
kind: Service
metadata:
  name: server1-service
spec:
  type: NodePort  # Set type to NodePort
  selector:
    app: nginx-service1  # This should match the labels in the Pods managed by the ReplicationController
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # Choose a port within the range 30000-32767
